[build]
  base = "client"
  publish = "dist"
  command = "npm install --include=dev && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./client/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_URL = "http://localhost:3000" # Replace with your actual backend URL
  NPM_FLAGS = "--no-audit --no-optional"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
