services:
  - type: web
    name: myportfolio
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_OPTIONAL
        value: false
      - key: NPM_CONFIG_FUND
        value: false
      - key: NPM_CONFIG_AUDIT
        value: false
