describe("Initial Recording 1 23/07/25 10:58AM", () => {
  it("tests Initial Recording 1 23/07/25 10:58AM", () => {
    cy.viewport(1068, 695);
    cy.visit("http://localhost:3000/");
    cy.get("#root > div > div > nav > button:nth-of-type(1)").click();
    cy.get("div.DualPanelContainer button:nth-of-type(1)").click();
    cy.get("div.DualPanelContainer button:nth-of-type(2)").click();
    cy.get("div.DualPanelContainer button:nth-of-type(3)").click();
    cy.get("div.DualPanelContainer button:nth-of-type(4)").click();
    cy.get("div.DualPanelContainer button:nth-of-type(2)").click();
    cy.get("div.LeftPanel > button:nth-of-type(1)").click();
    cy.get("#root > div").click();
    cy.get("nav > button:nth-of-type(2)").click();
    cy.get("button:nth-of-type(3)").click();
    cy.get("div.project-list > div:nth-of-type(2) button.right").click();
    cy.get("div.project-list > div:nth-of-type(2) button.right").click();
    cy.get("div.project-list > div:nth-of-type(2) button.right").click();
    cy.get("div.project-list > div:nth-of-type(2) div.project-description button").click();
    cy.get("button:nth-of-type(4)").click();
    cy.get("div.ServicesPanel > div:nth-of-type(2) img").click();
    cy.get("div:nth-of-type(3) img").click();
    cy.get("div.ServicesPanel > div:nth-of-type(2) li:nth-of-type(1)").click();
    cy.get("div.flipped p").click();
    cy.get("div:nth-of-type(4) img").click();
    cy.get("div.flipped p").click();
    cy.get("button:nth-of-type(5)").click();
    cy.get("button:nth-of-type(6)").click();
    cy.get("button:nth-of-type(1) > img").click();
    cy.get("input[type='text']").click();
    cy.get("input[type='text']").type("The Person");
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("desroches.boy@gmail.com");
    cy.get("input[type='password']").click();
    cy.get("input[type='password']").type("EpicUniverse123");
    cy.get("div.signup-panel button").click();
    cy.get("a").click();
    cy.get("input[type='email']").type("desroches.boy@gmail.com");
    cy.get("input[type='password']").type("EpicUniverse123");
    cy.get("div.signin-panel button").click();
    cy.get("#root > div > div button:nth-of-type(1) > img").click();
    cy.get("a svg").click();
    cy.get("nav > button:nth-of-type(1)").click();
    cy.get("#root > div > div button:nth-of-type(1) > img").click();
    cy.get("button:nth-of-type(2) > img").click();
    cy.get("#root > div > div button:nth-of-type(2) > img").click();
    cy.get("input[type='email']").type("desroches.boy@gmail.com");
    cy.get("input[type='password']").type("EpicUniverse123");
    cy.get("input[type='email']").click();
    cy.get("#root > div").click();
    cy.get("input[type='email']").type("");
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("admin@portfolio.com");
    cy.get("input[type='password']").dblclick();
    cy.get("input[type='password']").dblclick();
    cy.get("input[type='password']").type("admin123456");
    cy.get("div.signin-panel button").click();
    cy.get("button:nth-of-type(7)").click();
    cy.get("button:nth-of-type(8)").click();
    cy.get("button:nth-of-type(9)").click();
    cy.get("button:nth-of-type(11)").click();
    cy.get("button:nth-of-type(12)").click();
    cy.get("button:nth-of-type(13)").click();
    cy.get("a:nth-of-type(1) div.MuiListItemSecondaryAction-root svg").click();
    cy.get("button:nth-of-type(12)").click();
    cy.get("ul > div:nth-of-type(1) button").click();
    cy.get("button:nth-of-type(13)").click();
    cy.get("a:nth-of-type(4) div.MuiListItemSecondaryAction-root svg").click();
    cy.get("button:nth-of-type(1) > img").click();
    cy.get("a svg").click();
    cy.get("button:nth-of-type(1) > img").click();
    cy.get("button:nth-of-type(2) > img").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLBMBNBOBPBQBRBSBTBUBVBWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBBnBBoBBpBBqBBrBBsBBtBBuBBvBBwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BB+BB/BBgCBhCBiCBjCBkCBlCBmCB
